from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "tandemx.cli", *args],
        check=False,
        text=True,
        capture_output=True,
    )


def write_file(path: Path, text: str = "example\n") -> Path:
    path.write_text(text, encoding="utf-8")
    return path


def test_top_level_help() -> None:
    result = run_cli("--help")
    assert result.returncode == 0
    assert "discover" in result.stdout
    assert "quantify" in result.stdout
    assert "visualize" in result.stdout
    assert "simulate" in result.stdout


def test_subcommand_help() -> None:
    for command in ("discover", "quantify", "locate", "probe", "compare", "visualize", "simulate", "validate"):
        result = run_cli(command, "--help")
        assert result.returncode == 0
        assert "usage:" in result.stdout


def test_discover_help_is_de_novo() -> None:
    result = run_cli("discover", "--help")

    assert result.returncode == 0
    assert "--reads" in result.stdout
    assert "--outdir" in result.stdout
    assert "--catalog" not in result.stdout
    assert "--catalogue" not in result.stdout
    assert "--" + "tem" + "plate" not in result.stdout
    assert "--truth" not in result.stdout
    assert "known " + "repeat" not in result.stdout.lower()
    assert "reference " + "repeat" not in result.stdout.lower()


def test_downstream_catalog_help_points_to_discover_output() -> None:
    for command in ("quantify", "locate", "probe"):
        result = run_cli(command, "--help")
        assert result.returncode == 0
        assert "Repeat catalog FASTA generated by `tandemx discover`" in result.stdout


def test_missing_input_file_errors(tmp_path: Path) -> None:
    missing = tmp_path / "missing.fastq"
    result = run_cli(
        "discover",
        "--reads",
        str(missing),
        "--outdir",
        str(tmp_path / "out"),
    )
    assert result.returncode != 0
    assert f"Input file does not exist: {missing}" in result.stderr


def test_directory_input_path_errors(tmp_path: Path) -> None:
    input_dir = tmp_path / "reads_dir"
    input_dir.mkdir()

    result = run_cli(
        "discover",
        "--reads",
        str(input_dir),
        "--outdir",
        str(tmp_path / "out"),
    )

    assert result.returncode != 0
    assert f"Input path is not a file: {input_dir}" in result.stderr


def test_discover_writes_run_files(tmp_path: Path) -> None:
    reads = write_file(tmp_path / "reads.fa", ">r1\nACGTACGTACGTACGT\n")
    outdir = tmp_path / "discover"

    result = run_cli(
        "discover",
        "--reads",
        str(reads),
        "--outdir",
        str(outdir),
        "--min-monomer-len",
        "4",
        "--max-monomer-len",
        "8",
        "--min-support-reads",
        "1",
        "--min-repeat-span",
        "8",
    )

    assert result.returncode == 0
    assert "wrote" in result.stdout
    assert outdir.is_dir()
    assert (outdir / "run_config.yaml").is_file()
    assert (outdir / "run.log").is_file()
    assert (outdir / "candidate_reads.tsv").is_file()
    assert (outdir / "monomers.fa").is_file()
    assert (outdir / "families.tsv").is_file()
    config = (outdir / "run_config.yaml").read_text(encoding="utf-8")
    log = (outdir / "run.log").read_text(encoding="utf-8")
    assert 'command: "tandemx discover"' in config
    assert 'subcommand: "discover"' in config
    assert 'status: "discover_mvp_completed"' in config
    assert "cwd:" in config
    assert "argv:" in config
    assert "python_version:" in config
    assert "platform:" in config
    assert "func" not in config
    assert "command=tandemx discover" in log
    assert "status=discover_mvp_completed" in log
    assert f"output_directory={outdir}" in log


def test_each_subcommand_writes_run_config(tmp_path: Path) -> None:
    reads = write_file(tmp_path / "reads.fa", ">r1\nACGTACGTACGTACGT\n")
    catalogue = write_file(tmp_path / "repeat_catalogue.tsv")
    monomers = write_file(tmp_path / "monomers.fasta", ">m1\nACGT\n")
    assembly = write_file(tmp_path / "assembly.fa", ">chr1\nACGTACGT\n")
    copy_number = write_file(tmp_path / "copy_number.tsv")
    density = write_file(tmp_path / "repeat_density.tsv")
    arrays = write_file(tmp_path / "arrays.bed", "chr1\t0\t8\tm1\t1000\t.\thigh\t\n")
    probes = write_file(
        tmp_path / "probes.rank.tsv",
        "probe_id\tfamily_id\tsequence_length\tgc_content\ttm\testimated_copy_number\t"
        "arrayiness_score\tspecificity_score\toff_target_hits\tpredicted_regions\tprobe_score\tconfidence\twarning\n"
        "p1\tm1\t4\t0.5\t12\t1\t1\t1\t0\tchr1:0-8\t0.8\thigh\t\n",
    )
    comparison = write_file(
        tmp_path / "assembly_vs_read_cn.tsv",
        "family_id\tread_estimated_bp\tassembly_estimated_bp\tassembly_read_ratio\tstatus\tconfidence\twarning\n"
        "m1\t4\t8\t2\tconsistent\tmedium\t\n",
    )
    fish = write_file(
        tmp_path / "in_silico_fish.tsv",
        "probe_id\tchrom\tstart\tend\tpredicted_signal\tconfidence\twarning\n"
        "p1\tchr1\t0\t8\t0.8\thigh\t\n",
    )

    quantify_result = run_cli(
        "quantify",
        "--reads",
        str(reads),
        "--catalogue",
        str(monomers),
        "--genome-size",
        "16",
        "--k",
        "4",
        "--outdir",
        str(tmp_path / "quantify"),
    )
    quantify_outdir = tmp_path / "quantify"
    assert quantify_result.returncode == 0, quantify_result.stderr
    assert "copy-number estimates" in quantify_result.stdout
    assert (quantify_outdir / "copy_number.tsv").is_file()
    quantify_config = (quantify_outdir / "run_config.yaml").read_text(encoding="utf-8")
    assert 'command: "tandemx quantify"' in quantify_config
    assert 'subcommand: "quantify"' in quantify_config
    assert 'status: "quantify_mvp_completed"' in quantify_config
    assert "func" not in quantify_config

    locate_result = run_cli(
        "locate",
        "--assembly",
        str(assembly),
        "--catalogue",
        str(monomers),
        "--window-size",
        "4",
        "--step-size",
        "4",
        "--k",
        "4",
        "--outdir",
        str(tmp_path / "locate"),
    )
    locate_outdir = tmp_path / "locate"
    assert locate_result.returncode == 0, locate_result.stderr
    assert "arrays" in locate_result.stdout
    assert (locate_outdir / "repeat_density.bedgraph").is_file()
    assert (locate_outdir / "arrays.bed").is_file()
    assert (locate_outdir / "assembly_vs_read_cn.tsv").is_file()
    locate_config = (locate_outdir / "run_config.yaml").read_text(encoding="utf-8")
    assert 'command: "tandemx locate"' in locate_config
    assert 'subcommand: "locate"' in locate_config
    assert 'status: "locate_mvp_completed"' in locate_config
    assert "func" not in locate_config

    copy_number.write_text(
        "family_id\tmonomer_length\tdiagnostic_kmer_count\tmedian_kmer_depth\t"
        "haploid_depth\testimated_copy_number\testimated_bp\tconfidence\twarning\n"
        "m1\t4\t1\t1\t1\t1\t4\tmedium\t\n",
        encoding="utf-8",
    )
    probe_result = run_cli(
        "probe",
        "--catalogue",
        str(monomers),
        "--assembly",
        str(assembly),
        "--copy-number",
        str(copy_number),
        "--arrays",
        str(arrays),
        "--min-len",
        "4",
        "--max-len",
        "4",
        "--outdir",
        str(tmp_path / "probe"),
    )
    probe_outdir = tmp_path / "probe"
    assert probe_result.returncode == 0, probe_result.stderr
    assert "probes" in probe_result.stdout
    assert (probe_outdir / "probes.fa").is_file()
    assert (probe_outdir / "probes.rank.tsv").is_file()
    assert (probe_outdir / "in_silico_fish.tsv").is_file()
    probe_config = (probe_outdir / "run_config.yaml").read_text(encoding="utf-8")
    assert 'command: "tandemx probe"' in probe_config
    assert 'subcommand: "probe"' in probe_config
    assert 'status: "probe_mvp_completed"' in probe_config
    assert "func" not in probe_config

    visualize_result = run_cli(
        "visualize",
        "--catalogue",
        str(catalogue),
        "--copy-number",
        str(copy_number),
        "--locations",
        str(density),
        "--probes",
        str(probes),
        "--comparison",
        str(comparison),
        "--fish",
        str(fish),
        "--outdir",
        str(tmp_path / "visualize"),
    )
    visualize_outdir = tmp_path / "visualize"
    assert visualize_result.returncode == 0, visualize_result.stderr
    assert "plot files" in visualize_result.stdout
    assert (visualize_outdir / "catalogue_summary.svg").is_file()
    assert (visualize_outdir / "assembly_vs_read.svg").is_file()
    assert (visualize_outdir / "in_silico_fish.svg").is_file()
    visualize_config = (visualize_outdir / "run_config.yaml").read_text(encoding="utf-8")
    assert 'command: "tandemx visualize"' in visualize_config
    assert 'subcommand: "visualize"' in visualize_config
    assert 'status: "visualize_mvp_completed"' in visualize_config
    assert "func" not in visualize_config

    commands = [
        (
            "compare",
            [
                "compare",
                "--read-copy-number",
                str(copy_number),
                "--assembly-density",
                str(density),
                "--outdir",
                str(tmp_path / "compare"),
            ],
        ),
    ]

    for command, args in commands:
        result = run_cli(*args)
        outdir = tmp_path / command
        assert result.returncode == 0, result.stderr
        assert "deferred in this MVP" in result.stdout
        assert (outdir / "run_config.yaml").is_file()
        assert (outdir / "run.log").is_file()
        config = (outdir / "run_config.yaml").read_text(encoding="utf-8")
        assert f'command: "tandemx {command}"' in config
        assert f'subcommand: "{command}"' in config
        assert 'status: "skeleton_not_implemented"' in config
        assert "func" not in config
