"""Standalone offline HTML report for conservative TandemX family evidence."""
from __future__ import annotations

import html
import json
import math
import hashlib
from pathlib import Path
from typing import Any, Sequence

from tandemx.report_data import write_report_data


def _escape(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def _number(value: object) -> str:
    if value is None:
        return "NA"
    number = float(value)
    return f"{number:,.2f}" if math.isfinite(number) else "NA"


def _warning_text(value: object) -> str:
    return _escape(str(value or "").replace(";", "; ").replace("_", " "))


def _svg_cards(root: Path, figure_result: object) -> str:
    if not isinstance(figure_result, dict):
        return '<p class="muted">No current figure receipt was available.</p>'
    cards = []
    for key, value in figure_result.items():
        if not key.endswith("_svg"):
            continue
        path = Path(value)
        receipt_path = Path(figure_result.get(key.removesuffix("_svg") + "_receipt", ""))
        if not path.is_file() or not receipt_path.is_file():
            continue
        try:
            svg = path.read_text(encoding="utf-8")
            receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
            expected = receipt["files"]["svg"]["sha256"]
        except (OSError, KeyError, TypeError, json.JSONDecodeError):
            continue
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            continue
        # Figures are generated by TandemX code, but do not inline active SVG content.
        if "<script" in svg.lower() or "javascript:" in svg.lower():
            continue
        cards.append(f'<section class="figure">{svg}<p><a download href="{_escape(path.relative_to(root).as_posix())}">Download SVG</a></p></section>')
    return "".join(cards) or '<p class="muted">No summary figures were generated for this run.</p>'


def _recovery_status_text(summary: dict[str, Any]) -> str:
    counts = summary.get("recovery_status_counts", {})
    assessment = summary.get("recovery_assessment")
    assessment_text = ""
    if isinstance(assessment, dict):
        decision = assessment.get("decision")
        final_summary = assessment.get("summary")
        if decision or final_summary:
            assessment_text = (" Final recovery assessment"
                               + (f" ({_escape(decision)})" if decision else "")
                               + (f": {_escape(final_summary)}" if final_summary else "."))
    if not counts:
        return "No recovery candidates were reported." + assessment_text
    items = ", ".join(f"{_escape(status)}: {count}" for status, count in counts.items())
    return (f"Recovery candidate statuses: {items}. These are candidate-level outcomes; "
            "partially resolved is not a resolved assembly result." + assessment_text)


def _availability_warnings(data: dict[str, Any]) -> str:
    warnings = data.get("data_availability_warnings", [])
    if not warnings:
        return ""
    return "".join(f'<p class="alert"><strong>{_escape(row.get("code", "warning")).replace("_", " ")}.</strong> {_escape(row.get("message", ""))}</p>' for row in warnings)


def _recommended_cards(data: dict[str, Any]) -> str:
    rows = data.get("recommended_families", [])
    if not rows:
        return '<p class="muted">No family met the recorded comparison rule for possible under-representation.</p>'
    cards = []
    for row in rows:
        cards.append(
            '<article class="recommendation"><h3>' + _escape(row.get("family_id")) + '</h3>'
            + '<p><strong>Possible under-representation</strong>; confidence: '
            + _escape(row.get("confidence")) + '.</p><p>Estimated read–assembly abundance difference: '
            + _number(row.get("abundance_deficit_bp")) + ' bp.</p></article>'
        )
    return "".join(cards)


def _summary_cards(summary: dict[str, Any]) -> str:
    cards = [
        (summary.get("family_count"), "families observed"),
        (summary.get("high_confidence_family_count"), "families labelled high confidence"),
        (summary.get("possible_underrepresented_count"), "families with possible under-representation"),
        (summary.get("unresolved_family_count"), "families labelled unresolved"),
        (summary.get("low_confidence_family_count"), "families labelled low confidence"),
        (summary.get("architecture_edge_count"), "candidate family relationships"),
    ]
    assessment = summary.get("recovery_assessment")
    if isinstance(assessment, dict):
        for key, label in (("candidate_sequences", "recovery candidate sequences"),
                           ("validated_recovery_successes", "validated recovery successes")):
            if key in assessment:
                cards.append((assessment[key], label))
    return "".join(f'<div class="card"><div class="value">{_escape(value)}</div>{label}</div>'
                   for value, label in cards)


def write_html_report(outdir: Path, records: Sequence[object] = ()) -> None:
    """Write ``report.html`` and its conservative machine-readable companions."""
    root = Path(outdir)
    data = write_report_data(root, records)
    from tandemx.report_figures import write_report_figures
    figures = write_report_figures(root, data)
    summary = data["summary"]
    family_rows = "".join(
        "<tr>" + "".join(f"<td>{_escape(value)}</td>" for value in (
            row["family_id"], row["representative_monomer_id"], _number(row["monomer_length_bp"]),
            _number(row["support_read_count"]), _number(row["estimated_abundance_bp"]),
            _number(row["assembly_representation_bp"]), _number(row["assembly_read_ratio"]),
            row["confidence"], _warning_text(row["warning"]),
        )) + "</tr>"
        for row in data["families"]
    )
    source_rows = "".join(
        f'<li><a download href="{_escape(source["path"])}">{_escape(source["path"])}</a>: '
        f'{"used" if source["used"] else "not used (not a validated successful stage or absent)"}'
        f'{("; SHA-256 " + _escape(source["sha256"]) + "; " + str(source["bytes"]) + " bytes") if source.get("sha256") else ""}</li>'
        for source in data["sources"]
    )
    metadata_rows = "".join(f'<li>{_escape(item["path"])}; SHA-256 {_escape(item["sha256"])}; {item["bytes"]} bytes</li>' for item in data.get("provenance", {}).get("files", []))
    command_rows = "".join(f'<li>{_escape(item.get("step"))}: <code>{_escape(item.get("command"))}</code> (exit {_escape(item.get("exit_status"))}; validated {_escape(item.get("output_validated"))})</li>' for item in data.get("provenance", {}).get("commands", []))
    payload = json.dumps(data, ensure_ascii=False).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    page = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TandemX family evidence report</title><style>
body{{font:16px system-ui,sans-serif;margin:auto;max-width:1200px;padding:1.25rem;color:#172028;background:#fafcff}} h1{{margin-bottom:.2rem}} .lead{{font-size:1.1rem;max-width:70ch}} .cards,.recommendations{{display:flex;gap:.7rem;flex-wrap:wrap}} .card,.recommendation{{background:white;border:1px solid #d5deea;border-radius:9px;padding:.8rem;min-width:150px}} .recommendation{{max-width:300px}} .recommendation h3{{margin:.1rem 0}} .value{{font-size:1.55rem;font-weight:700}} .alert{{background:#fff4df;border-left:4px solid #c87a15;padding:.7rem}} table{{width:100%;border-collapse:collapse;background:white}} th,td{{padding:.45rem;border-bottom:1px solid #dce3ec;text-align:left;vertical-align:top}} th{{position:sticky;top:0;background:#eef4fb;cursor:pointer}} input{{width:min(420px,100%);padding:.55rem;margin:.8rem 0}} .muted{{color:#566575}} .figure{{background:white;border:1px solid #d5deea;border-radius:9px;padding:.6rem;margin:.8rem 0;overflow:auto}} .figure svg{{max-width:100%;height:auto}} details{{margin:.8rem 0}} @media(max-width:700px){{body{{padding:.7rem}} table{{font-size:.82rem}} th,td{{padding:.28rem}}}}
</style></head><body>
<main><h1>TandemX family evidence</h1>{_availability_warnings(data)}<p class="lead">This run reports discovered repeat-family evidence and, where validated inputs exist, read-based abundance and assembly representation. Candidate period multiples are not validated higher-order repeats; read–assembly differences are estimates, not physical missing-base truth.</p>
<section class="cards">{_summary_cards(summary)}</section>
<h2>Families recommended for evidence review</h2><p class="muted">Families whose estimated read abundance exceeds assembly representation under the recorded comparison rule. Review confidence and warnings before interpretation.</p><section class="recommendations">{_recommended_cards(data)}</section>
<h2>Evidence overview</h2>{_svg_cards(root, figures)}
<h2>Bounded recovery candidates</h2><p class="muted">{_recovery_status_text(summary)}</p>
<details><summary>Full family table</summary><label for="filter">Filter families</label><br><input id="filter" placeholder="family ID, confidence, warning…" autocomplete="off"><p class="muted">Select a column heading to sort. NA means no validated value was available. Warnings are rendered as readable labels.</p><table id="families"><thead><tr><th>Family</th><th>Representative</th><th>Length bp</th><th>Supporting reads</th><th>Estimated abundance bp</th><th>Assembly representation bp</th><th>Assembly/read ratio</th><th>Confidence</th><th>Recorded warnings</th></tr></thead><tbody>{family_rows}</tbody></table></details>
<details><summary>Methods, provenance, commands, and downloadable products</summary><p>Only outputs from validated successful pipeline stages are included when step records were supplied. Existing files from failed, skipped, or absent stages are excluded.</p><h3>Used products</h3><ul>{source_rows}<li><a download href="summary.tsv">summary.tsv</a></li><li><a download href="summary.json">summary.json</a></li><li><a download href="families/family_network.graphml">family network GraphML</a></li><li><a download href="families/repeat_architecture.tsv">architecture evidence table</a></li></ul><h3>Run metadata hashes</h3><ul>{metadata_rows or '<li>No local run metadata was available.</li>'}</ul><h3>Recorded commands</h3><ul>{command_rows or '<li>No pipeline step records were supplied.</li>'}</ul></details>
</main><script id="report-data" type="application/json">{payload}</script><script>
const table=document.querySelector('#families'), body=table.tBodies[0]; document.querySelector('#filter').oninput=e=>{{let q=e.target.value.toLowerCase();for(const row of body.rows)row.hidden=!row.textContent.toLowerCase().includes(q)}}; [...table.tHead.rows[0].cells].forEach((head,col)=>head.onclick=()=>{{let rows=[...body.rows], asc=head.dataset.asc!=='1'; rows.sort((a,b)=>a.cells[col].textContent.localeCompare(b.cells[col].textContent,undefined,{{numeric:true}})*(asc?1:-1));rows.forEach(r=>body.append(r));[...table.tHead.rows[0].cells].forEach(h=>delete h.dataset.asc);head.dataset.asc=asc?'1':'0'}});
</script></body></html>'''
    (root / "report.html").write_text(page, encoding="utf-8")
